name: crazyswarm
dependencies:
  - numpy
  - matplotlib
  - vispy
  - pyyaml
  - swig
  - sphinx
  - sphinx_rtd_theme
  - pyqt
  - conda-forge::sphinx-argparse
  - conda-forge::sphinx-tabs
  - pytest
  - snakeviz
  - scipy
