/crazyflie_server:
  ros__parameters:
    # simulation related
    sim:
      max_dt: 0 #0.1              # artificially limit the step() function (set to 0 to disable)
      backend: np                 # see backend folder for a list 
      visualizations:             # see visualizition folder for a list
        - rviz
        # - pdf
      controller: mellinger # none, pid, mellinger
