/crazyflie_server:
  ros__parameters:
    # simulation related
    sim:
      max_dt: 0 #0.1              # artificially limit the step() function (set to 0 to disable)
      backend: basicnumpy
      visualizations:
        # - rviz
        - pdf
